In [40]:
import pandas as pd
import numpy as np

## Data Source
##### https://www.amfiindia.com/downloads
##### http://portal.amfiindia.com/DownloadSchemeData_Po.aspx?mf=0

In [95]:
df=pd.read_csv("SchemeData.csv")

## Lets look at some numbers about data

#### Shape of Data (Rows, Columns)

In [81]:
df.shape

(18843, 9)

#### Size of Data Total Number of Rows and columns (Rows * Columns)

In [83]:
df.size

169587

#### Dimenstion of Data (used for representation in N-Dimensional Space)

In [86]:
df.ndim

2

## Preview Data

#### First and Last Five records

In [55]:
df.head()

,AMC,Code,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
0,Aditya Birla Sun Life AMC Limited,100033,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund - ...,5000,24-Feb-95,24-Feb-95,INF209K01165
1,Aditya Birla Sun Life AMC Limited,100034,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund -R...,5000,24-Feb-95,24-Feb-95,INF209K01157INF209K01CE5
2,Aditya Birla Sun Life AMC Limited,119433,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund - ...,5000,24-Feb-95,24-Feb-95,INF209K01VG0INF209K01VI6
3,Aditya Birla Sun Life AMC Limited,119436,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund - ...,5000,24-Feb-95,24-Feb-95,INF209K01VH8
4,Aditya Birla Sun Life AMC Limited,100037,Aditya Birla Sun Life Income Fund,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Quarterly ...,5000,1-Jan-94,1-Jan-94,INF209K01587INF209K01CY3

In [62]:
df.tail()

,AMC,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
18838,ICICI Prudential Asset Management Company Limited,ICICI Prudential Fixed Maturity Plan - Series ...,Close Ended,Income,ICICI Prudential Fixed Maturity Plan - Series ...,5000,27-May-19,NaN,NaN
18839,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Growth Option,5000,28-May-19,NaN,NaN
18840,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Direct Plan - Grow...,5000,28-May-19,NaN,NaN
18841,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Direct Plan - Divi...,5000,28-May-19,NaN,NaN
18842,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Dividend Option,5000,28-May-19,NaN,NaN

#### First N records

In [64]:
df.head(7)

,AMC,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
0,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund - ...,5000,24-Feb-95,24-Feb-95,INF209K01165
1,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund -R...,5000,24-Feb-95,24-Feb-95,INF209K01157INF209K01CE5
2,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund - ...,5000,24-Feb-95,24-Feb-95,INF209K01VG0INF209K01VI6
3,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Equity Advantage Fund,Open Ended,Equity Scheme - Large & Mid Cap Fund,Aditya Birla Sun Life Equity Advantage Fund - ...,5000,24-Feb-95,24-Feb-95,INF209K01VH8
4,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Income Fund,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Quarterly ...,5000,1-Jan-94,1-Jan-94,INF209K01587INF209K01CY3
5,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Income Fund,Open Ended,Debt Scheme - Medium to Long Duration Fund,Aditya Birla Sun Life Income Fund - Growth - R...,5000,1-Jan-94,1-Jan-94,INF209K01579
6,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Income Fund,Open Ended,Debt Scheme - Medium to Long Duration Fund,Birla Income Plus-Institutional (Growth),5000,1-Jan-94,1-Jan-94,NaN

#### Last N records

In [65]:
df.tail(7)

,AMC,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
18836,ICICI Prudential Asset Management Company Limited,ICICI Prudential Fixed Maturity Plan - Series ...,Close Ended,Income,ICICI Prudential Fixed Maturity Plan - Series ...,5000,27-May-19,NaN,NaN
18837,ICICI Prudential Asset Management Company Limited,ICICI Prudential Fixed Maturity Plan - Series ...,Close Ended,Income,ICICI Prudential Fixed Maturity Plan - Series ...,5000,27-May-19,NaN,NaN
18838,ICICI Prudential Asset Management Company Limited,ICICI Prudential Fixed Maturity Plan - Series ...,Close Ended,Income,ICICI Prudential Fixed Maturity Plan - Series ...,5000,27-May-19,NaN,NaN
18839,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Growth Option,5000,28-May-19,NaN,NaN
18840,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Direct Plan - Grow...,5000,28-May-19,NaN,NaN
18841,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Direct Plan - Divi...,5000,28-May-19,NaN,NaN
18842,ICICI Prudential Asset Management Company Limited,ICICI Prudential MNC Fund,Open Ended,Equity Scheme - Sectoral/ Thematic,ICICI Prudential MNC Fund - Dividend Option,5000,28-May-19,NaN,NaN

#### Access Range of Records
*Ex: Access records starting from 15th record up to 20th record*

In [74]:
df[14:20]

,AMC,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
14,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Liquid Fund,Open Ended,Debt Scheme - Liquid Fund,Aditya Birla Sun Life Liquid Fund-Retail (Growth),5000,4-Jun-97,7-Jun-97,INF209K01ME4
15,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Liquid Fund,Open Ended,Debt Scheme - Liquid Fund,Aditya Birla Sun Life Liquid Fund-Institutiona...,5000,4-Jun-97,7-Jun-97,INF209K01RT1
16,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Liquid Fund,Open Ended,Debt Scheme - Liquid Fund,Aditya Birla Sun Life Liquid Fund-Retail (Divi...,5000,4-Jun-97,7-Jun-97,INF209K01KP4
17,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Liquid Fund,Open Ended,Debt Scheme - Liquid Fund,Aditya Birla Sun Life Liquid Fund - Daily Divi...,5000,4-Jun-97,7-Jun-97,INF209K01KQ2INF209K01SQ5
18,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Liquid Fund,Open Ended,Debt Scheme - Liquid Fund,Aditya Birla Sun Life Liquid Fund - Growth,5000,4-Jun-97,7-Jun-97,INF209K01RU9
19,Aditya Birla Sun Life AMC Limited,Aditya Birla Sun Life Liquid Fund,Open Ended,Debt Scheme - Liquid Fund,Aditya Birla Sun Life Liquid Fund- Discipline ...,5000,4-Jun-97,7-Jun-97,INF209K01KZ3

In [103]:
df.describe()

                Code
count   18843.000000
mean   131357.410763
std     12984.539718
min    100033.000000
25%    122405.500000
50%    134955.000000
75%    142137.500000
max    147348.000000

In [102]:
df1= df.drop(columns=['Code'])
df1.describe()

,AMC,Scheme Name,Scheme Type,Scheme Category,Scheme NAV Name,Scheme Minimum Amount,Launch Date,Closure Date,ISIN Div Payout/ ISIN GrowthISIN Div Reinvestment
count,18843,18843,18843,18843,18843,18801,18827,6364,17000
unique,43,3734,3,51,18801,392,1936,909,16989
top,ICICI Prudential Asset Management Company Limited,LIC MF Unit Linked Insurance Scheme (ULIS),Close Ended,Income,Kotak Bond-Deposit-Dividend,5000,14-Jan-03,8-Oct-09,INF204KB1RN2
freq,2936,36,12114,11805,4,6882,87,50,2

In [45]:
df['Scheme Category'].unique().tolist()

['Equity Scheme - Large & Mid Cap Fund',
 'Debt Scheme - Medium to Long Duration Fund',
 'Debt Scheme - Liquid Fund',
 'Debt Scheme - Gilt Fund',
 'Equity Scheme - Sectoral/ Thematic',
 'Equity Scheme - ELSS',
 'Debt Scheme - Medium Duration Fund',
 'Equity Scheme - Multi Cap Fund',
 'Hybrid Scheme - Aggressive Hybrid Fund',
 'Debt Scheme - Money Market Fund',
 'Hybrid Scheme - Balanced Hybrid Fund',
 'Other Scheme - Index Funds',
 'Debt Scheme - Dynamic Bond',
 'Equity Scheme - Small Cap Fund',
 'Equity Scheme - Large Cap Fund',
 'Equity Scheme - Value Fund',
 'Debt Scheme - Long Duration Fund',
 'Balanced',
 'Equity Scheme - Mid Cap Fund',
 'Debt Scheme - Low Duration Fund',
 'Debt Scheme - Corporate Bond Fund',
 'Solution Oriented Scheme - Retirement Fund',
 'Gilt',
 'Hybrid Scheme - Conservative Hybrid Fund',
 'Growth',
 'Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage',
 'Solution Oriented Scheme - Children s Fund',
 'ELSS',
 'Debt Scheme - Overnight Fund',
 'Income',
 'Hybrid Scheme - Multi Asset Allocation',
 'Debt Scheme - Floater Fund',
 'Debt Scheme - Short Duration Fund',
 'Debt Scheme - Ultra Short Duration Fund',
 'Liquid',
 'Hybrid Scheme - Equity Savings',
 'Equity Scheme - Focussed Fund',
 'Debt Scheme - Credit Risk Fund',
 'Other Scheme - Other  ETFs',
 'Equity Scheme - Dividend Yield Fund',
 'Other Scheme - FoF Domestic',
 'Other Scheme - FoF Overseas',
 'Floating Rate',
 'Assured Return',
 'Equity Scheme - Contra Fund',
 'Money Market',
 'Debt Scheme - Banking and PSU Fund',
 'Hybrid Scheme - Arbitrage Fund',
 'Other Scheme - Gold ETF',
 'Debt Scheme - Gilt Fund with 10 year constant duration',
 'Fund of Funds - Overseas']